Repository Loss-Leader-Project/Fontend, pull requests merged in 2022-03, with the labels that each got.

#22 Add : 리뷰 페이지네이션 구현중
  package-lock.json
  package.json
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Pages.jsx
  src/pages/Detail/ProductReview.jsx
  src/pages/Detail/TopReview.jsx
  src/utils/api.js
Labels: Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#26 Add : 리스트페이지 페이지네이션 개발
  package-lock.json
  package.json
  public/data/food-gold.json
  public/data/food-hotplay.json
  public/data/food-silver.json
  public/images/delivery.svg
  public/images/food-removebg.png
  public/images/packaging.svg
  public/images/storeMeal.svg
  public/index.html
  src/Components/Nav.jsx
  src/Routers.jsx
  src/hooks/useFirstRender.jsx
  src/pages/Detail/Pages.jsx
  src/pages/List/Card.jsx
  src/pages/List/Fliters.jsx
  src/pages/List/List.jsx
  src/styles/globalStyle.js
  src/utils/api.js
Labels: Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#25 Add : 네이버/카카오 로그인, 리덕스 세팅, 모든 모달 구현 및 수정완료, 햄버거 메뉴 추가, 토큰 API 구현, 아이디 중복 체크 추가
  package-lock.json
  package.json
  public/data/emailcode.json
  public/data/findpassword.json
  public/images/kakao_login_large_narrow.png
  public/images/kakao_login_medium_narrow.png
  public/index.html
  src/App.jsx
  src/Components/HamburgerMenu.jsx
  src/Components/Header.jsx
  src/Routers.jsx
  src/modules/Store.js
  src/modules/reducers/loginReducer.js
  src/pages/LogIn/LogIn.jsx
  src/pages/LogIn/LoginNaver.jsx
  src/pages/LogIn/SearchID/LoginSearchID.jsx
  src/pages/LogIn/SearchPW/FindPasswordModalBody.jsx
  src/pages/LogIn/SearchPW/LoginSearchPW.jsx
  src/pages/LogIn/api.js
  src/pages/Main/MainInfoProject.jsx
  src/pages/Main/MainSlider.jsx
  src/pages/Main/listApi.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpEmailCheck.jsx
  src/pages/SignUp/SignUpEmailLayout.jsx
  src/pages/SignUp/SignUpIDLayout.jsx
  src/pages/SignUp/SignUpInput.jsx
  src/pages/SignUp/SignUpPostNumber.jsx
  src/pages/SignUp/SignUpPostNumberLayout.jsx
  src/pages/SignUp/SignupEmailSubmit.jsx
  src/pages/SignUp/api.js
  src/pages/SignUp/check.js
  src/utils/OAuth.js
  src/utils/api.js
Labels: Status: Self Refactoring 완료, Status: Merge 승인 요청

#29 Improve : MUI 공통태그 모듈화 진행 / 로그아웃 API 적용
  public/data/mainfood-bestreview.json
  src/Components/HamburgerMenu.jsx
  src/Components/Header.jsx
  src/Components/MuiButton.jsx
  src/Components/MuiInput.jsx
  src/pages/LogIn/LogIn.jsx
  src/pages/LogIn/LoginEmailLayout.jsx
  src/pages/LogIn/LoginInput.jsx
  src/pages/LogIn/SearchID/LoginSearchID.jsx
  src/pages/LogIn/SearchPW/LoginSearchPW.jsx
  src/pages/Main/MainCard.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpAdressInput.jsx
  src/pages/SignUp/SignUpEmail.jsx
  src/pages/SignUp/SignUpEmailLayout.jsx
  src/pages/SignUp/SignUpIDLayout.jsx
  src/pages/SignUp/SignUpInput.jsx
  src/pages/SignUp/SignUpPostNumber.jsx
  src/pages/SignUp/SignupEmailSubmit.jsx
  src/styles/theme.js
  src/utils/api.js
Labels: Status: Peer 리뷰 요청

#27 Add : 마이페이지 회원정보 수정 개발
  public/data/user.json
  src/Components/common/Button.jsx
  src/Components/common/Input.jsx
  src/Components/common/Title.jsx
  src/contexts/ModifyProvider.jsx
  src/pages/My/Modify/AdditionalInfo.jsx
  src/pages/My/Modify/BasicInfo.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/Modify/PasswordModifyForm.jsx
  src/utils/api.js
  src/utils/validation.js
Labels: Status: Peer 리뷰 요청

#28 Add : 리뷰 등록 개발
  package-lock.json
  package.json
  src/Components/Editor.jsx
  src/Components/common/Input.jsx
  src/contexts/ModifyProvider.jsx
  src/pages/My/Modify/AdditionalInfo.jsx
  src/pages/My/Modify/BasicInfo.jsx
  src/pages/My/Modify/PasswordModifyForm.jsx
  src/pages/My/My.jsx
  src/pages/My/ReviewInsert/ReviewInsertPage.jsx
  src/pages/My/ReviewInsert/Row.jsx
  src/utils/api.js
  src/utils/validation.js
Labels: Status: Peer 리뷰 요청

#31 Improve : 메인페이지 랜덤추천 구현(라우팅 시, 추천받기 버튼 클릭 시 작동)
  public/data/menuList.json
  src/pages/Main/RecommandBox.jsx
Labels: Status: Peer 리뷰 요청

#30 Add : validation emptyValues 추가
  src/utils/validation.js
Labels: Status: Peer 리뷰 요청

#35 Add 공통 api 구현
  package-lock.json
  src/pages/Apply/Apply.jsx
  src/pages/Detail/Detail.jsx
  src/utils/apiBaseUrl.js
  src/utils/apiConfig.js
  src/utils/apiInterceptors.js
  src/utils/apiUrl.js
  src/utils/httpErrorMessage.js
Labels: Status: Peer 리뷰 요청

#37 Add : Input 공통 컴포넌트 적용중
  public/data/applyTitle.json
  src/pages/Apply/AgreeUsePersonalInfo.jsx
  src/pages/Apply/Apply.jsx
  src/pages/Apply/ApplyInput.jsx
  src/pages/Apply/ColumnTitle.jsx
  src/pages/Apply/MuiCheckbox.jsx
  src/pages/Apply/OrdererInfo.jsx
  src/pages/Apply/PaymentInfo.jsx
  src/pages/Apply/ProductInfoSummary.jsx
  src/pages/Apply/Title.jsx
  src/pages/Apply/TopImg.jsx
Labels: Status: Peer 리뷰 요청

#36 Add : Footer 구현 완료
  public/data/footerData.json
  src/Components/Footer.jsx
  src/Routers.jsx
Labels: Status: Peer 리뷰 요청

#38 Fix : token check api 수정
  src/utils/api.js
Labels: Status: Peer 리뷰 요청

#33 Fix : 공통 MUI로 수정, 폴더 정리
  public/data/food-gold.json
  public/data/food-hotplay.json
  public/data/food-silver.json
  public/index.html
  src/Components/Button.jsx
  src/Components/Editor.jsx
  src/Components/MuiInput.jsx
  src/Components/Title.jsx
  src/Components/common/Input.jsx
  src/Routers.jsx
  src/contexts/CouponProvider.jsx
  src/contexts/ModifyProvider.jsx
  src/contexts/OrdersProvider.jsx
  src/hooks/useFirstRender.jsx
  src/pages/List/Card.jsx
  src/pages/List/List.jsx
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Buy/GridItem.jsx
  src/pages/My/Buy/Order.jsx
  src/pages/My/Buy/Orders.jsx
  src/pages/My/Buy/OrdersHead.jsx
  src/pages/My/Coupon/CouponHistory.jsx
  src/pages/My/Coupon/CouponInput.jsx
  src/pages/My/Coupon/CouponPage.jsx
  src/pages/My/Coupon/Coupons.jsx
  src/pages/My/Coupon/History.jsx
  src/pages/My/Modify/AdditionalInfo.jsx
  src/pages/My/Modify/BasicInfo.jsx
  src/pages/My/Modify/GridContainer.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/Modify/PasswordModifyForm.jsx
  src/pages/My/My.jsx
  src/pages/My/MyMenu.jsx
  src/pages/My/Review/Insert/InsertPage.jsx
  src/pages/My/Review/Review.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/pages/My/Review/Reviews.jsx
  src/pages/My/ReviewInsert/Row.jsx
Labels: Status: Peer 리뷰 요청

#40 Fix : 공통 API 모듈 수정
  src/Components/Editor.jsx
  src/pages/List/List.jsx
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Coupon/History.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/Review/Insert/InsertPage.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/utils/api.js
  src/utils/apiConfig.js
  src/utils/apiInterceptors.js
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#41 Add : 리스트 페이지 API 연결 및 코드 리팩토링
  .env
  public/data/food-gold.json
  public/data/food-hotplay.json
  public/data/food-silver.json
  src/Components/Nav.jsx
  src/Routers.jsx
  src/pages/List/Filters.jsx
  src/pages/List/Fliters.jsx
  src/pages/List/List.jsx
  src/utils/apiBaseUrl.js
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#42 Add : 회원수정 페이지 API 연결 및 코드 리팩토링
  public/data/user.json
  src/pages/My/Modify/ModifyPage.jsx
  src/utils/apiConfig.js
  src/utils/apiInterceptors.js
  src/utils/apiUrl.js
  src/utils/httpErrorMessage.js
  src/utils/validation.js
Labels: Status: Peer 리뷰 요청

#43 Add : 업체 리뷰 페이지 API 연결 및 코드 리팩토링
  .env
  public/data/reviewData.json
  src/Components/Empty.jsx
  src/pages/List/List.jsx
  src/pages/My/Review/Filter.jsx
  src/pages/My/Review/Review.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/utils/apiConfig.js
  src/utils/apiInterceptors.js
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#46 Fix : 회원정보 수정 API 변경에 대해서 코드 수정 및 추가 개발
  src/pages/My/Modify/ModifyPage.jsx
Labels: Status: Peer 리뷰 요청

#45 Add: Detail API 반영 완료, 리뷰 아직
  .env
  public/data/DetailData.json
  public/data/newDetailData.json
  src/Components/Pages.jsx
  src/Routers.jsx
  src/pages/Detail/AvailabilityMeals.jsx
  src/pages/Detail/BottomReview.jsx
  src/pages/Detail/Carousel.jsx
  src/pages/Detail/Description.jsx
  src/pages/Detail/DescriptionColumn.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/MenuBar.jsx
  src/pages/Detail/NaverMapApi.jsx
  src/pages/Detail/ProductInfo.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/pages/Detail/ProductReview.jsx
  src/pages/Detail/TopReview.jsx
  src/pages/Detail/changeImageUrl.js
  src/pages/TeamsInfo/TeamsInfo.jsx
  src/utils/apiBaseUrl.js
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#47 Add : 구매 내역 페이지 API 연결 및 리팩토링
  public/data/orders.json
  src/Components/Button.jsx
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Buy/BuysHead.jsx
  src/pages/My/Buy/BuysItem.jsx
  src/pages/My/Buy/GridItem.jsx
  src/pages/My/Buy/UserInfo.jsx
  src/pages/My/Coupon/History.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/MyMenu.jsx
  src/pages/My/Review/Review.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/utils/api.js
  src/utils/apiBaseUrl.js
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#52 Fix : 헴버거 메뉴 css 수정 및 로그아웃 수정, 메인페이지 리뷰 라우팅 추가 및 리뷰 이미지 없을때 UI 추가, 404페이지 구현 및 적용, 네이버/카카오 로그인 오류 해결, 함수 모듈화 구현
  src/Components/HamburgerMenu.jsx
  src/Components/Header.jsx
  src/Components/MuiInput.jsx
  src/Error404.jsx
  src/Routers.jsx
  src/pages/LogIn/LogIn.jsx
  src/pages/LogIn/LoginNaver.jsx
  src/pages/LogIn/SearchID/LoginSearchID.jsx
  src/pages/LogIn/SearchPW/FindPasswordModalBody.jsx
  src/pages/LogIn/SearchPW/LoginSearchPW.jsx
  src/pages/LogIn/api.js
  src/pages/Main/MainCard.jsx
  src/pages/Main/RecommandBox.jsx
  src/pages/Main/listApi.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpEmailLayout.jsx
  src/pages/SignUp/SignUpIDLayout.jsx
  src/pages/SignUp/SignUpInput.jsx
  src/pages/SignUp/SignUpPostNumber.jsx
  src/pages/SignUp/SignupEmailSubmit.jsx
  src/pages/SignUp/api.js
  src/utils/EnterKey.js
  src/utils/OAuth.js
  src/utils/TokenCheck.js
  src/utils/api.js
  src/utils/apiConfig.js
  src/utils/check.js
Labels: Status: Peer 리뷰 요청

#51 Add : 팀원소개 UI 개발
  package-lock.json
  public/data/buys.json
  public/data/team.json
  public/index.html
  src/Components/Editor.jsx
  src/Components/Footer.jsx
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Buy/BuysItem.jsx
  src/pages/My/Review/Insert/InsertPage.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/pages/TeamsInfo/TeamsInfo.jsx
  src/utils/apiUrl.js
Labels: Status: Peer 리뷰 요청

#53 Fix : 리뷰이미지 없을 경우 메인 카드 UI 수정
  src/Routers.jsx
  src/pages/Main/MainCard.jsx
Labels: Status: Peer 리뷰 요청

#54 Add : 업체 리뷰 등록 API 연결 및 리팩토링
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/Review/Insert/InsertPage.jsx
  src/pages/My/Review/ReviewPage.jsx
Labels: Status: Peer 리뷰 요청

#50 Add Apply api 연결중 Detail API 로딩
  public/data/applyData.json
  public/data/reviewData.json
  src/Components/Footer.jsx
  src/Routers.jsx
  src/pages/Apply/AgreeUsePersonalInfo.jsx
  src/pages/Apply/Apply.jsx
  src/pages/Apply/OrdererInfo.jsx
  src/pages/Apply/PaymentInfo.jsx
  src/pages/Apply/ProductInfoSummary.jsx
  src/pages/Apply/TopImg.jsx
  src/pages/Completion/Completion.jsx
  src/pages/Detail/Carousel.jsx
  src/pages/Detail/DescriptionColumn.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/MenuBar.jsx
  src/pages/Detail/NaverMapApi.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/pages/Detail/ProductReview.jsx
  src/utils/apiUrl.js
  src/utils/changeImageUrl.js
Labels: Status: 기능 구현중
