Repository Loss-Leader-Project/Fontend, pull requests merged in 2022-02, with the labels that each got.

#4 Add :상단 이미지 레이아웃 구현, hover시 이미지 변경
  package-lock.json
  package.json
  public/data/detailPhoto.json
  pull_request_template.md
  src/App.jsx
  src/Routers.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/ProductInfo.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/styles/theme.js
Labels: Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#3 Add : Header component 추가
  public/images/LossLeader_logo_pc.png
  readme
  src/Components/Header.jsx
  src/pages/Main/Main.jsx
Labels: Status: Rebase 완료, Status: Peer 리뷰 진행 중

#7 Add : Info 레이아웃 구현 완료,반응형은 아직 않됨
  package-lock.json
  package.json
  public/data/detailInfo.json
  public/images/DetailPageApply.png
  public/images/DetailPageApplyBlock.png
  src/pages/Detail/Detail.jsx
  src/pages/Detail/ProductInfo.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/pages/Detail/Tag.jsx
  src/styles/theme.js
Labels: Status: Rebase 완료, Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#12 Fix : mui theme, mui styles 제거
  .prettierrc
  package-lock.json
  package.json
  public/data/food-gold.json
  public/data/food-hotplay.json
  public/data/food-silver.json
  public/images/food.jpg
  src/App.jsx
  src/Components/Nav.jsx
  src/pages/List/Card.jsx
  src/pages/List/Fliters.jsx
  src/pages/List/List.jsx
  src/styles/muiTheme.js
Labels: Status: Rebase 완료, Status: Peer 리뷰 요청

#9 Add : 로그인 페이지 구현
  package-lock.json
  src/Components/Header.jsx
  src/Routers.jsx
  src/pages/LogIn/LogIn.jsx
Labels: Status: Peer 리뷰 요청, Status: Refactoring 진행중

#10 Add : 아이디 및 비밀번호 찾기 페이지 UI 구현 및 Header 컴포넌트 라우터 기능 추가
  src/Components/Header.jsx
  src/Routers.jsx
  src/pages/LogIn/LoginSearchID.jsx
  src/pages/LogIn/LoginSearchPW.jsx
  src/pages/Main/Main.jsx
Labels: Status: Refactoring 진행중

#13 Add : 회원가입 UI + 우편번호 카카오 라이브러리 적용
  public/index.html
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpAdressInput.jsx
  src/pages/SignUp/SignUpEmail.jsx
  src/pages/SignUp/SignUpEmailCheck.jsx
  src/pages/SignUp/SignUpEmailLayout.jsx
  src/pages/SignUp/SignUpInput.jsx
  src/pages/SignUp/SignUpPostNumber.jsx
  src/pages/SignUp/SignUpPostNumberLayout.jsx
Labels: Status: Peer 리뷰 요청

#14 Add : 메인페이지 UI 구현
  public/data/mainfood-bestreview.json
  public/data/mainfood-hotplace.json
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  src/Routers.jsx
  src/pages/List/Card.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainCard.jsx
  src/pages/Main/MainList.jsx
  src/pages/Main/MainSlider.jsx
  src/pages/Main/RecommandBox.jsx
Labels: Status: Peer 리뷰 요청

#11 Add: 메뉴바 Tab으로 구현중,Description 부분 레이아웃 구상중
  package-lock.json
  package.json
  public/data/detailInfo.json
  public/data/detailPhoto.json
  public/data/newDetailData.json
  src/Routers.jsx
  src/pages/Detail/AvailabilityMeals.jsx
  src/pages/Detail/Description.jsx
  src/pages/Detail/DescriptionColumn.jsx
  src/pages/Detail/DescriptionMenuInfo.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/MenuBar.jsx
  src/pages/Detail/ProductInfo.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/pages/Detail/Review.jsx
  src/pages/Detail/Tag.jsx
  src/pages/List/Fliters.jsx
Labels: Status: Rebase 완료, Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#16 Add : 마이페이지 UI 구현
  package-lock.json
  public/data/coupons.json
  public/data/orders.json
  public/data/reviews.json
  public/index.html
  src/App.jsx
  src/Components/MyMenu.jsx
  src/Components/common/Button.jsx
  src/Components/common/Input.jsx
  src/Components/common/Title.jsx
  src/Components/coupon/CouponHistory.jsx
  src/Components/coupon/CouponInput.jsx
  src/Components/coupon/Coupons.jsx
  src/Components/modify/AdditionalInfo.jsx
  src/Components/modify/BasicInfo.jsx
  src/Components/nav/Nav.jsx
  src/Components/order/Order.jsx
  src/Components/order/Orders.jsx
  src/Components/order/OrdersHead.jsx
  src/Components/order/UserInfo.jsx
  src/Components/review/Review.jsx
  src/Components/review/Reviews.jsx
  src/Routers.jsx
  src/contexts/CouponProvider.jsx
  src/contexts/ModifyProvider.jsx
  src/contexts/OrdersProvider.jsx
  src/pages/List/Card.jsx
  src/pages/List/Fliters.jsx
  src/pages/List/List.jsx
  src/pages/My/BuyPage.jsx
  src/pages/My/CouponPage.jsx
  src/pages/My/ModifyPage.jsx
  src/pages/My/My.jsx
  src/pages/My/ReviewPage.jsx
  src/styles/theme.js
Labels: Status: Rebase 완료

#17 Improve : 회원가입, 로그인 등 페이지 별 JS 기능 구현
  package-lock.json
  public/index.html
  src/Components/Header.jsx
  src/Routers.jsx
  src/pages/LogIn/LogIn.jsx
  src/pages/LogIn/LoginInput.jsx
  src/pages/LogIn/SearchID/LoginSearchID.jsx
  src/pages/LogIn/SearchPW/LoginSearchPW.jsx
  src/pages/LogIn/check.js
  src/pages/Main/MainList.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpAdressInput.jsx
  src/pages/SignUp/SignUpEmail.jsx
  src/pages/SignUp/SignUpEmailCheck.jsx
  src/pages/SignUp/SignUpEmailLayout.jsx
  src/pages/SignUp/SignUpInput.jsx
  src/pages/SignUp/SignUpPostNumber.jsx
  src/pages/SignUp/SignUpPostNumberLayout.jsx
  src/pages/SignUp/check.js
  src/utils/api.js
Labels: Status: Merge 승인 요청

#19 Add : 리뷰 View 단 구현, 이미지 Carousel 아직
  package-lock.json
  public/data/newDetailData.json
  src/pages/Detail/AvailabilityMeals.jsx
  src/pages/Detail/BottomReview.jsx
  src/pages/Detail/Carousel.jsx
  src/pages/Detail/Description.jsx
  src/pages/Detail/DescriptionColumn.jsx
  src/pages/Detail/DescriptionMenuInfo.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/MenuBar.jsx
  src/pages/Detail/NaverMapApi.jsx
  src/pages/Detail/ProductInfo.jsx
  src/pages/Detail/ProductPhoto.jsx
  src/pages/Detail/ProductReview.jsx
  src/pages/Detail/Review.jsx
  src/pages/Detail/TopReview.jsx
Labels: Status: Peer 리뷰 요청, Status: Self Refactoring 완료

#20 Fix : 프로젝트 폴더 구조 변경
  package-lock.json
  src/Components/Nav.jsx
  src/Components/common/Button.jsx
  src/Components/common/Title.jsx
  src/Routers.jsx
  src/pages/My/Buy/BuyPage.jsx
  src/pages/My/Buy/Order.jsx
  src/pages/My/Buy/Orders.jsx
  src/pages/My/Buy/OrdersHead.jsx
  src/pages/My/Buy/UserInfo.jsx
  src/pages/My/Coupon/CouponHistory.jsx
  src/pages/My/Coupon/CouponInput.jsx
  src/pages/My/Coupon/CouponPage.jsx
  src/pages/My/Coupon/Coupons.jsx
  src/pages/My/Modify/AdditionalInfo.jsx
  src/pages/My/Modify/BasicInfo.jsx
  src/pages/My/Modify/ModifyPage.jsx
  src/pages/My/My.jsx
  src/pages/My/MyMenu.jsx
  src/pages/My/Review/Review.jsx
  src/pages/My/Review/ReviewPage.jsx
  src/pages/My/Review/Reviews.jsx
Labels: Status: Peer 리뷰 요청
